config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/people_app_development.rb
class PeopleAppDevelopment < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update(people_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end

  def create
    @person = Person.new(people_params)

    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  private

    def people_params
      params.require(:person).permit(:character, :age, :hair_color, :eye_color, :gender, :house, :city, :quotes, :alive, :pets)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Edit Characters', people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game of Thrones Wiki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="shortcut icon" type="image/png" href="lib/assets/a70953080a754032a3cf729716a7e4b4.ico/android-icon-192x192.png"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/people/delete.html.erb
<h1>People#delete</h1>
<p>Find me in app/views/people/delete.html.erb</p>

app/views/people/edit.html.erb
<h1>Edit character</h1>
<%= form_for @person do |f| %>
    <%= f.label :character %>
    <%= f.text_field :character %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>

    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>

    <%= f.label :gender %>
    <%= f.text_field :gender %>

    <%= f.label :house %>
    <%= f.text_field :house %>

    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :quotes %>
    <%= f.text_field :quotes %>

    <%= f.label :alive %>
    <%= f.text_field :alive %>

    <%= f.label :pet %>
    <%= f.text_field :pet %>

    <%= f.submit %>


<% end %>

app/views/people/index.html.erb
<h3> The Cast </h3>
<p><%= link_to 'New character', new_person_path %></p>

<% @people.each do |person| %>

    <h2><%= person.character %></h2>
    
    <%= link_to 'Edit', edit_person_path(person) %>
    <%= link_to 'DELETE', person, method: :delete %>
    <%= link_to 'More info', person_path(person) %>
    
<% end %>

app/views/people/new.html.erb
<h1>New character</h1>
<%= form_for @person do |f| %>
  <%= f.label :character %>
    <%= f.text_field :character %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>
    <br>
    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>

    <%= f.label :gender %>
    <%= f.text_field :gender %>

    <%= f.label :house %>
    <%= f.text_field :house %>
    <br>
    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :quotes %>
    <%= f.text_field :quotes %>

    <%= f.label :alive %>
    <%= f.text_field :alive %>
    <br>
    <%= f.label :pet %>
    <%= f.text_field :pet %>
    <%= f.submit %>
    <% puts Faker::TvShows::GameOfThrones.character%>
<% end %>

app/views/people/show.html.erb
<h1>Name: <%= @person.character %></h1>
<h4>Age: <%= @person.age %></h1>
<h4>Hair color: <%= @person.hair_color %></h1>
<h4>Eye color: <%= @person.eye_color %></h1>
<h4>Gender: <%= @person.gender %></h1>
<h4>House: <%= @person.house %></h1>
<h4>City: <%= @person.city %></h1>
<h4>Quote: <%= @person.quotes %></h1>
<h4>Vitals: <%= @person.alive %></h1>
<h4>Pets: <%= @person.pet %></h1>

<%= link_to 'Back', people_path %>

app/views/static_pages/about.html.erb
<h1>About</h1>
<a href="http://localhost:3000/">Home Link</a>

<p>Create, view, update, delete Game of Thrones characters. Cannot be blank</p>

<h1>People</h1>

<p>Character #=> "Tyrion Lannister"</p>

<p>Age (validates for number) #=> 25</p>

<p>Hair_color #=> Black</p>

<p>Eye_color #=> Green</p>

<p>Gender #=> Man</p>

<h2>Alive #=> No</h2>

<p>House #=> "Stark"</p>

<p>City #=> "Lannisport"</p>

<p>Quote #=> "Never forget who you are. The rest of the world won't. Wear it like an armor and it can never be used against you."</p>

<h1>Dragons</h1>

<p>Dragon #=> "Drogon"</p>

<p>Age #=> "7</p>

<p>Color #=> Red</p>

<h2>Alive #=> No</h2>

app/views/static_pages/home.html.erb
<h1>Not helpful home</h1>
<a href="http://localhost:3000/">Home Link</a>